// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _430testmvc.Data;

#nullable disable

namespace _430testmvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.3.22175.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_430testmvc.Models.Book", b =>
                {
                    b.Property<int>("book_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("book_ID"), 1L, 1);

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("book_borrow_ID")
                        .HasColumnType("int");

                    b.Property<string>("book_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("publicsh")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("user_ID")
                        .HasColumnType("int");

                    b.HasKey("book_ID");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
